name: "land"
mode: "dev"
port: 8080
version: "v0.0.1"
start_time: "2024-12-03"
machine_id: "123456"

log:
  level: "debug"
  filename: "log/app.log"
  max_size: 100
  max_age: 30
  max_backups: 10

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "land"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

auth:
  jwt_expire: 3600